//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBS_DA_BI_Application.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AXMbsDevBIDAEntities : DbContext
    {
        public AXMbsDevBIDAEntities()
            : base("name=AXMbsDevBIDAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CUSTINVOICEJOUR> CUSTINVOICEJOURs { get; set; }
        public DbSet<CUSTINVOICETRAN> CUSTINVOICETRANS { get; set; }
        public DbSet<CUSTTABLE> CUSTTABLEs { get; set; }
        public DbSet<DATAAREA> DATAAREAs { get; set; }
        public DbSet<MBSBDSALESREPTABLE> MBSBDSALESREPTABLEs { get; set; }
        public DbSet<MBSWBWEBUSERCONTACT> MBSWBWEBUSERCONTACTs { get; set; }
    }
}
