//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBS_DA_BI_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATAAREA
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public long RECID { get; set; }
    }
}
